#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Platform Smith - Epic Board (cross-repo workflow conductor)
# =============================================================================
# Read-only dashboard for an epic→work cross-repo workflow. Computes the global
# phase barrier + relay-settle state and prints a single "DO THIS NEXT" so you
# never have to guess which repo (terminal tab) to work on.
#
# Model (see docs/dev/decisions/epic-conductor-barrier-workflow.md):
#   - An epic advances ONE phase at a time across ALL its repos:
#       requirements -> planning -> implementation -> validation
#   - No repo starts phase P+1 until every repo has settled phase P AND there
#     are zero open relays.
#   - Relay state is DERIVED from each child's append-only event log
#     (<work>/work.jsonl): open = relay_sent/relay_received minus relay_resolved
#     (by direction+slug). Legacy fallback: count files under <work>/upstream/.
#     (See docs/dev/decisions/append-only-work-event-log.md.)
#   - Read-only by default. With --write it injects the derived Tracked Repos
#     table + Epic Phase line into the epic manifest between BOARD anchors
#     (the only sanctioned writer of those derived sections).
#
# Usage:
#   ./scripts/epic-board.sh [epic-id] [--watch] [--write]
#       epic-id   short (epic-2607...) or full id; omit => most-recently-modified epic
#       --watch   refresh every 5s (Ctrl-C to exit)
#       --write   regenerate the epic manifest's derived board between
#                 <!-- BEGIN BOARD --> / <!-- END BOARD --> anchors
#
# Reads, per tracked repo, the work manifest field (generated by wrender.sh):
#   **Epic Phase Done**: requirements | planning | implementation | validation
# (falls back to the Phase column word if the field is absent).
# =============================================================================

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WATCH=0
WRITE=0
EPIC_ARG=""

for a in "$@"; do
  case "$a" in
    --watch) WATCH=1 ;;
    --write) WRITE=1 ;;
    -h|--help) sed -n '2,42p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) EPIC_ARG="$a" ;;
  esac
done

# ---- phase ladder ----------------------------------------------------------
# ordinal: 0=none 1=requirements 2=planning 3=implementation 4=validation 5=done
phase_ord() {
  case "$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')" in
    *complete*|*done*)        echo 5 ;;
    *validat*)                echo 4 ;;
    *implement*)              echo 3 ;;
    *plan*)                   echo 2 ;;
    *requirement*)            echo 1 ;;
    *) echo 0 ;;
  esac
}
phase_name() { case "$1" in 1) echo requirements;; 2) echo planning;; 3) echo implementation;; 4) echo validation;; 5) echo done;; *) echo "(pre-requirements)";; esac; }
phase_cmd()  {
  case "$1" in
    1) echo "/work <work-id>  (research + requirements)" ;;
    2) echo "/planv0 --work <work-id>" ;;
    3) echo "/implement_plan <work>/plans/master.md" ;;
    4) echo "validate / run tests" ;;
    *) echo "—" ;;
  esac
}

# ---- resolve epic dir ------------------------------------------------------
resolve_epic() {
  local arg="$1" d
  if [[ -n "$arg" ]]; then
    if [[ -f "$ROOT/docs/epics/$arg/manifest.md" ]]; then echo "$ROOT/docs/epics/$arg"; return; fi
    local m=( "$ROOT"/docs/epics/"$arg"*/manifest.md )
    if [[ -f "${m[0]:-}" ]]; then echo "$(dirname "${m[0]}")"; return; fi
    echo "ERR: epic '$arg' not found" >&2; return 1
  fi
  # most recently modified epic manifest
  d="$(ls -t "$ROOT"/docs/epics/*/manifest.md 2>/dev/null | head -1 || true)"
  [[ -n "$d" ]] || { echo "ERR: no epics found" >&2; return 1; }
  dirname "$d"
}

# ---- work dir for a repo + workitem ---------------------------------------
work_dir() {
  local repo="$1" wid="$2"
  if [[ "$repo" == "solution" ]]; then echo "$ROOT/docs/work/$wid"; else echo "$ROOT/repos/$repo/docs/work/$wid"; fi
}

# relay_counts <wd>  -> echoes "<open-inbound> <open-outbound>"
# New model: fold work.jsonl (relay_sent/received minus relay_resolved by dir+slug).
# Legacy fallback: count files under <wd>/upstream/.
relay_counts() {
  local wd="$1" oin=0 oout=0
  if [[ -f "$wd/work.jsonl" ]] && command -v jq >/dev/null 2>&1; then
    oin=$(jq -rs '(map(select(.type=="relay_resolved")|(.direction+"/"+.slug))) as $r
                  | [ .[] | select(.type=="relay_received")
                      | select((("inbound/"+.slug)) as $k | ($r|index($k))|not) ] | length' "$wd/work.jsonl")
    oout=$(jq -rs '(map(select(.type=="relay_resolved")|(.direction+"/"+.slug))) as $r
                   | [ .[] | select(.type=="relay_sent")
                       | select((("outbound/"+.slug)) as $k | ($r|index($k))|not) ] | length' "$wd/work.jsonl")
  elif [[ -d "$wd/upstream" ]]; then
    oin=$(find "$wd/upstream" -maxdepth 1 -name 'from-*.md' 2>/dev/null | wc -l | tr -d ' ')
    oout=$(find "$wd/upstream" -maxdepth 1 -name 'to-*.md' 2>/dev/null | wc -l | tr -d ' ')
  fi
  echo "${oin:-0} ${oout:-0}"
}

# relay_list <wd> <repo>  -> one "  repo: <dir> <peer> — <slug>" per OPEN relay.
relay_list() {
  local wd="$1" repo="$2"
  if [[ -f "$wd/work.jsonl" ]] && command -v jq >/dev/null 2>&1; then
    jq -rs --arg repo "$repo" '
      (map(select(.type=="relay_resolved")|(.direction+"/"+.slug))) as $r
      | [ .[] | select(.type=="relay_sent" or .type=="relay_received")
          | {dir:(if .type=="relay_sent" then "outbound" else "inbound" end), slug:.slug, peer:(.to // .from // "—")} ]
      | map(select(((.dir+"/"+.slug)) as $k | ($r|index($k))|not))
      | .[] | "  \($repo): \(.dir) \(.peer) — \(.slug)"' "$wd/work.jsonl"
  elif [[ -d "$wd/upstream" ]]; then
    find "$wd/upstream" -maxdepth 1 \( -name 'from-*.md' -o -name 'to-*.md' \) 2>/dev/null \
      | sed "s|.*/||; s|^|  ${repo}: |"
  fi
}

# inject_block <file> <begin-marker> <end-marker> <content-file>
# Replaces the region between the markers with the content; if the markers are
# absent, appends them (with content) at end of file. Deterministic, in-place.
inject_block() {
  local file="$1" begin="$2" end="$3" cf="$4"
  if grep -qF "$begin" "$file"; then
    awk -v b="$begin" -v e="$end" -v cf="$cf" '
      index($0,b){ print; while((getline line < cf)>0) print line; close(cf); skip=1; next }
      index($0,e){ skip=0; print; next }
      !skip { print }
    ' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
  else
    { echo ""; echo "$begin"; cat "$cf"; echo "$end"; } >> "$file"
  fi
}

# discover_children <epic-id>  -> "repo|wid" per work item whose log declares this epic.
# Membership is DERIVED: each child declares its epic at creation
# (wlog.sh created ... epic=<id>), so the epic never hand-maintains a roster.
# Sorted + de-duped. (render falls back to the manifest table for legacy epics.)
discover_children() {
  local epic_id="$1" f wd wid repo belongs
  command -v jq >/dev/null 2>&1 || return 0
  for f in "$ROOT"/docs/work/*/work.jsonl "$ROOT"/repos/*/docs/work/*/work.jsonl; do
    [[ -f "$f" ]] || continue
    belongs="$(jq -rs --arg e "$epic_id" 'any(.[]; (.type=="created" or .type=="meta_changed") and (.epic==$e))' "$f" 2>/dev/null || echo false)"
    [[ "$belongs" == "true" ]] || continue
    wd="$(dirname "$f")"; wid="$(basename "$wd")"
    repo="$(jq -rs 'map(select(.type=="created"))[0].repo // empty' "$f" 2>/dev/null)"
    if [[ -z "$repo" ]]; then
      if [[ "$wd" == "$ROOT/repos/"* ]]; then repo="${wd#"$ROOT"/repos/}"; repo="${repo%%/*}"; else repo="solution"; fi
    fi
    echo "$repo|$wid"
  done | sort -u
}

render() {
  local EPIC_DIR EPIC_MD EPIC_ID EPIC_TITLE
  EPIC_DIR="$(resolve_epic "$EPIC_ARG")" || exit 1
  EPIC_MD="$EPIC_DIR/manifest.md"
  EPIC_ID="$(basename "$EPIC_DIR")"
  EPIC_TITLE="$(awk -F'— ' '/^# Epic:/{print $2; exit}' "$EPIC_MD")"
  local EPIC_PHASE; EPIC_PHASE="$(awk -F': ' '/^\*\*Epic Phase\*\*:/{print $2; exit}' "$EPIC_MD" | sed 's/ *$//')"
  local WISH; WISH="$(awk -F': ' '/^\*\*Wishlist\*\*:/{print $2; exit}' "$EPIC_MD" | sed 's/ *$//')"
  # "Last Synced" was removed from the manifest in the event-log rewrite; show the
  # authored "Last Updated" instead (sync-time is no longer a stored field).
  local UPDATED; UPDATED="$(awk -F': ' '/^\*\*Last Updated\*\*:/{print $2; exit}' "$EPIC_MD" | cut -c1-10)"

  # Membership: DERIVED from child logs (each declares epic=<id> at creation).
  # Legacy fallback: parse the manifest's Tracked Repos table for older epics
  # whose children predate the event log.
  local ROWS; ROWS="$(discover_children "$EPIC_ID")"
  if [[ -z "$ROWS" ]]; then
    ROWS="$(awk '
      /^## Tracked Repos/{intable=1; next}
      /^## /{ if(intable) exit }
      intable && /^\| / {
        n=split($0,c,"|");
        repo=c[2]; wid=c[3]; phase=c[4];
        gsub(/^[ \t]+|[ \t]+$/,"",repo); gsub(/^[ \t]+|[ \t]+$/,"",wid); gsub(/^[ \t]+|[ \t]+$/,"",phase);
        if(repo=="Repo" || repo ~ /^-+$/ || repo=="") next;
        print repo "|" wid "|" phase;
      }' "$EPIC_MD")"
  fi

  # gather per-repo state
  local base=99 total_open=0
  local -a R_repo R_wid R_phase R_done R_in R_out R_state
  local i=0
  while IFS='|' read -r repo wid phasecell; do
    [[ -n "$repo" ]] || continue
    local wd; wd="$(work_dir "$repo" "$wid")"
    # Epic Phase Done: prefer the event log (last phase_done); fall back to the
    # generated manifest field, then the legacy table cell.
    local donejson=""
    [[ -f "$wd/work.jsonl" ]] && command -v jq >/dev/null 2>&1 && \
      donejson="$(jq -rs 'map(select(.type=="phase_done")|.phase)|(last // "")' "$wd/work.jsonl" 2>/dev/null)"
    local donefield=""
    [[ -z "$donejson" && -f "$wd/manifest.md" ]] && donefield="$(awk -F': ' '/^\*\*Epic Phase Done\*\*:/{print $2; exit}' "$wd/manifest.md" | sed 's/ *$//')"
    local doneword="${donejson:-${donefield:-$phasecell}}"
    local dord; dord="$(phase_ord "$doneword")"
    local oin oout; read -r oin oout < <(relay_counts "$wd")
    R_repo[$i]="$repo"; R_wid[$i]="$wid"; R_phase[$i]="$doneword"; R_done[$i]="$dord"; R_in[$i]="$oin"; R_out[$i]="$oout"
    (( dord < base )) && base=$dord
    total_open=$(( total_open + oin + oout ))
    i=$(( i+1 ))
  done <<< "$ROWS"
  local n=$i
  (( base==99 )) && base=0
  local target=$(( base + 1 )); (( target > 5 )) && target=5

  # per-repo state label
  for ((j=0;j<n;j++)); do
    if (( ${R_in[$j]} > 0 )); then R_state[$j]="🟢 ACT — ${R_in[$j]} inbound ask(s); answer + reply"
    elif (( ${R_out[$j]} > 0 )); then R_state[$j]="⏳ BLOCKED — ${R_out[$j]} reply pending (run /epic sync)"
    elif (( ${R_done[$j]} >= 4 )); then R_state[$j]="✅ complete (validated)"
    elif (( ${R_done[$j]} == base )); then R_state[$j]="🔵 WORKING — owes $(phase_name $target)"
    else R_state[$j]="✅ settled @ $(phase_name ${R_done[$j]}) (at barrier)"; fi
  done

  # ---- header ----
  printf '\033[1m%s\033[0m\n' "EPIC $EPIC_ID"
  [[ -n "$EPIC_TITLE" ]] && printf '  %s\n' "$EPIC_TITLE"
  printf '  phase: \033[1m%s\033[0m   ·   wishlist: %s   ·   last updated: %s\n' "${EPIC_PHASE:-$(phase_name $base)}" "${WISH:-—}" "${UPDATED:---}"
  printf '%s\n' "────────────────────────────────────────────────────────────────────────────"
  printf '%-14s %-34s %-14s %s\n' "REPO" "WORK ITEM" "DONE" "STATE"
  for ((j=0;j<n;j++)); do
    printf '%-14s %-34s %-14s %s\n' "${R_repo[$j]}" "${R_wid[$j]:0:34}" "${R_phase[$j]}" "${R_state[$j]}"
  done
  printf '%s\n' "────────────────────────────────────────────────────────────────────────────"

  # ---- NEXT ----
  local NEXT="" STATEMSG=""
  if (( total_open > 0 )); then
    STATEMSG="⏳ Settling $(phase_name $target) — relays in flight (barrier held)"
    # bottleneck = repo with open inbound (it unblocks the chain)
    local actrepo=""
    for ((j=0;j<n;j++)); do (( ${R_in[$j]} > 0 )) && { actrepo="${R_repo[$j]} (${R_wid[$j]})"; break; }; done
    if [[ -n "$actrepo" ]]; then
      NEXT="👉 open the ${actrepo%% *} tab → read upstream/from-*, validate, reply if needed. Then run /epic sync at root."
    else
      NEXT="👉 run  /epic sync  at the solution root to deliver $total_open pending relay(s)."
    fi
  elif (( base >= 4 )); then
    # validation is the terminal phase — every tracked repo has settled it (and zero
    # open relays, or we'd be in the settling branch above) ⇒ the epic is complete.
    STATEMSG="✅ All repos settled validation — epic complete."
    NEXT="🎉 Epic complete — set the epic manifest Status: Completed (and /epic next-milestone if wishlist-linked)."
  else
    STATEMSG="▶ $(phase_name $base) settled — barrier OPEN, advance to $(phase_name $target)"
    local laggards=""
    for ((j=0;j<n;j++)); do (( ${R_done[$j]} == base )) && laggards+="${R_repo[$j]} "; done
    NEXT="👉 run  $(phase_cmd $target)  in: ${laggards% }"
  fi
  printf '%s\n' "$STATEMSG"
  printf '\033[1m%s\033[0m\n' "$NEXT"

  # ---- open relay detail ----
  if (( total_open > 0 )); then
    printf '%s\n' "open relays:"
    for ((j=0;j<n;j++)); do
      local wd; wd="$(work_dir "${R_repo[$j]}" "${R_wid[$j]}")"
      relay_list "$wd" "${R_repo[$j]}"
    done
  fi

  # ---- --write: inject the derived board into the epic manifest ----
  if (( WRITE )); then
    local barrier_phase; barrier_phase="$(phase_name "$base")"
    # validation settled across all repos with no open relays ⇒ complete
    if (( base >= 4 && total_open == 0 )); then barrier_phase="complete"; fi
    local bf; bf="$(mktemp)"
    {
      printf '**Epic Phase**: %s\n\n' "$barrier_phase"
      printf '| Repo | Work Item | Phase | Status |\n'
      printf '|------|-----------|-------|--------|\n'
      for ((j=0;j<n;j++)); do
        # Status cell: plain-text projection of the per-repo state (emoji stripped is fine to keep).
        printf '| %s | %s | %s | %s |\n' "${R_repo[$j]}" "${R_wid[$j]}" "${R_phase[$j]}" "${R_state[$j]}"
      done
    } > "$bf"
    inject_block "$EPIC_MD" "<!-- BEGIN BOARD -->" "<!-- END BOARD -->" "$bf"
    rm -f "$bf"
    printf '\033[2m%s\033[0m\n' "ⓘ wrote derived board into $EPIC_MD (between BOARD anchors)."
  else
    printf '\033[2m%s\033[0m\n' "ⓘ read-only snapshot. Run with --write to refresh the epic manifest board, or /epic board (Claude) to sync-then-show."
  fi
}

if (( WATCH )); then
  while true; do clear; render; printf '\n(refreshing every 5s · Ctrl-C to exit)\n'; sleep 5; done
else
  render
fi
