#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Platform Smith - Epic Board (cross-repo workflow conductor)
# =============================================================================
# Read-only dashboard for an epic→work cross-repo workflow. Computes the global
# phase barrier + relay-settle state and prints a single "DO THIS NEXT" so you
# never have to guess which repo (terminal tab) to work on.
#
# Model (see docs/dev/decisions/epic-conductor-barrier-workflow.md):
#   - An epic advances ONE phase at a time across ALL its repos:
#       requirements -> planning -> implementation -> validation
#   - No repo starts phase P+1 until every repo has settled phase P AND there
#     are zero open relays.
#   - Relay state is DERIVED from each child's append-only event log
#     (<work>/work.jsonl). A relay is ONE thing shared by two repos, keyed by
#     slug; a leg (relay_sent on the source, relay_received on the target) is
#     OPEN until the relay is settled — and ONE relay_resolved for that slug
#     ANYWHERE in the epic closes BOTH legs (the "A1" rule — see relay_counts).
#     So a source's outbound leg auto-closes when the target resolves; the
#     source never has to emit its own resolution. Legacy fallback: count files
#     under <work>/upstream/. (See docs/dev/decisions/append-only-work-event-log.md.)
#   - Read-only by default. With --write it injects the derived Tracked Repos
#     table + Epic Phase line into the epic manifest between BOARD anchors
#     (the only sanctioned writer of those derived sections).
#
# Usage:
#   ./scripts/epic-board.sh [epic-id] [--watch] [--write]
#       epic-id   short (epic-2607...) or full id; omit => most-recently-modified epic
#       --watch   refresh every 5s (Ctrl-C to exit)
#       --write   regenerate the epic manifest's derived board between
#                 <!-- BEGIN BOARD --> / <!-- END BOARD --> anchors
#
# Reads, per tracked repo, the work manifest field (generated by wrender.sh):
#   **Epic Phase Done**: requirements | planning | implementation | validation
# (falls back to the Phase column word if the field is absent).
#
# CROSS-PLATFORM (Windows/msys + Linux): every jq call that reads a work.jsonl
# feeds the file via STDIN redirection (`jq '…' < "$f"`), NEVER as a path arg
# (`jq '…' "$f"`). $ROOT is an absolute msys POSIX path (/c/…); a native-Windows
# jq (e.g. chocolatey's) cannot open such a path when MSYS_NO_PATHCONV=1 is set
# (common in docker-heavy shells) — it fails "Could not open file", returns
# empty, and under `set -euo pipefail` the whole board silently renders zero
# repos / exits 2. Redirecting the file into stdin lets bash open it (bash
# understands msys paths) and hands jq a stream — portable everywhere. Keep this
# invariant for any new jq-reads-a-file call here and in wrender.sh.
# =============================================================================

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WATCH=0
WRITE=0
EPIC_ARG=""

for a in "$@"; do
  case "$a" in
    --watch) WATCH=1 ;;
    --write) WRITE=1 ;;
    -h|--help) sed -n '2,42p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) EPIC_ARG="$a" ;;
  esac
done

# ---- phase ladder ----------------------------------------------------------
# ordinal: 0=none 1=requirements 2=planning 3=implementation 4=validation 5=done
phase_ord() {
  case "$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')" in
    *complete*|*done*)        echo 5 ;;
    *validat*)                echo 4 ;;
    *implement*)              echo 3 ;;
    *plan*)                   echo 2 ;;
    *requirement*)            echo 1 ;;
    *) echo 0 ;;
  esac
}
phase_name() { case "$1" in 1) echo requirements;; 2) echo planning;; 3) echo implementation;; 4) echo validation;; 5) echo done;; *) echo "(pre-requirements)";; esac; }
phase_cmd()  {
  case "$1" in
    1) echo "/work <work-id>  (research + requirements)" ;;
    2) echo "/planv0 --work <work-id>" ;;
    3) echo "/implement_plan <work>/plans/master.md" ;;
    4) echo "validate / run tests" ;;
    *) echo "—" ;;
  esac
}
# repo_cwd <repo> -> directory to open a Claude session in (solution alias → root).
repo_cwd() { if [[ "$1" == "solution" ]]; then echo "."; else echo "repos/$1"; fi; }
# phase_slash <ord> <wid> <repo> -> the exact command (with the real work id) for that phase.
# Validation is TWO-LAYER (see the barrier decision doc): every child repo runs its LOCAL suite and
# relays its e2e-needs to solution; SOLUTION (the epic owner) authors + drives the cross-repo e2e and
# is the final gate. So the validation command differs for solution vs a child repo.
phase_slash() {
  local ord="$1" wid="$2" repo="${3:-}"
  case "$ord" in
    1) echo "/work $wid" ;;
    2) echo "/planv0 --work $wid" ;;
    3) echo "/implement_plan docs/work/$wid/plans/master.md" ;;
    4) if [[ "$repo" == "solution" ]]; then
         echo "author + DRIVE the cross-repo e2e (epic Success Criteria) on a live stack — you are the e2e gate; resolve each repo's e2e-needs relay as it's covered+passing, then: scripts/wlog.sh docs/work/$wid phase_done phase=validation"
       else
         echo "run LOCAL suite; then relay e2e-needs → solution: write relays/outbound/to-solution--$repo-e2e-needs.md + scripts/wlog.sh docs/work/$wid relay_sent to=solution slug=$repo-e2e-needs relay_kind=blocks phase=validation ask=\"e2e coverage for $repo\"; then settle: scripts/wlog.sh docs/work/$wid phase_done phase=validation"
       fi ;;
    *) echo "/work $wid" ;;
  esac
}
# open_inbound_slugs <wd> <resolved-slugs> -> space-separated slugs of this repo's OPEN
# inbound relays: received here and NOT settled anywhere in the epic (the epic-global
# <resolved-slugs> set — see the A1 rule in relay_counts).
open_inbound_slugs() {
  local wd="$1" resolved="${2:-}"
  [[ -f "$wd/work.jsonl" ]] && command -v jq >/dev/null 2>&1 || return 0
  jq -rs --arg res "$resolved" '
    ($res|split(" ")|map(select(length>0))) as $r
    | [ .[] | select(.type=="relay_received") | select(.slug as $s | ($r|index($s))|not) | .slug ] | join(" ")' < "$wd/work.jsonl"
}

# ---- resolve epic dir ------------------------------------------------------
resolve_epic() {
  local arg="$1" d
  if [[ -n "$arg" ]]; then
    if [[ -f "$ROOT/docs/epics/$arg/manifest.md" ]]; then echo "$ROOT/docs/epics/$arg"; return; fi
    local m=( "$ROOT"/docs/epics/"$arg"*/manifest.md )
    if [[ -f "${m[0]:-}" ]]; then echo "$(dirname "${m[0]}")"; return; fi
    echo "ERR: epic '$arg' not found" >&2; return 1
  fi
  # most recently modified epic manifest
  d="$(ls -t "$ROOT"/docs/epics/*/manifest.md 2>/dev/null | head -1 || true)"
  [[ -n "$d" ]] || { echo "ERR: no epics found" >&2; return 1; }
  dirname "$d"
}

# ---- work dir for a repo + workitem ---------------------------------------
work_dir() {
  local repo="$1" wid="$2"
  if [[ "$repo" == "solution" ]]; then echo "$ROOT/docs/work/$wid"; else echo "$ROOT/repos/$repo/docs/work/$wid"; fi
}

# relay_counts <wd> <resolved-slugs>  -> echoes "<open-inbound> <open-outbound>"
#
# A1 RULE — a relay is ONE thing shared by two repos; ONE resolution closes BOTH legs.
# A relay (identified by its slug) is SETTLED once ANY relay_resolved for that slug exists
# ANYWHERE in the epic (the epic-global <resolved-slugs> set computed by epic_resolved_slugs).
# Both the target's inbound leg (relay_received) and the source's OUTBOUND leg (relay_sent)
# are then closed. This is the fix for dangling outbound legs: the source used to only ever
# emit relay_synced (never a resolution), so relay_sent counted as open forever. Now the
# outbound auto-closes the moment the target resolves — no separate direction=outbound event
# needed. Legacy fallback: count files under <wd>/upstream/.
relay_counts() {
  local wd="$1" resolved="${2:-}" oin=0 oout=0
  if [[ -f "$wd/work.jsonl" ]] && command -v jq >/dev/null 2>&1; then
    oin=$(jq -rs --arg res "$resolved" '($res|split(" ")|map(select(length>0))) as $r
          | [ .[] | select(.type=="relay_received") | select(.slug as $s | ($r|index($s))|not) ] | length' < "$wd/work.jsonl")
    oout=$(jq -rs --arg res "$resolved" '($res|split(" ")|map(select(length>0))) as $r
          | [ .[] | select(.type=="relay_sent") | select(.slug as $s | ($r|index($s))|not) ] | length' < "$wd/work.jsonl")
  elif [[ -d "$wd/upstream" ]]; then
    oin=$(find "$wd/upstream" -maxdepth 1 -name 'from-*.md' 2>/dev/null | wc -l | tr -d ' ')
    oout=$(find "$wd/upstream" -maxdepth 1 -name 'to-*.md' 2>/dev/null | wc -l | tr -d ' ')
  fi
  echo "${oin:-0} ${oout:-0}"
}

# relay_list <wd> <repo> <resolved-slugs>  -> one "  repo: <dir> <peer> — <slug>" per OPEN
# relay leg (slug not in the epic-global resolved set — see the A1 rule in relay_counts).
relay_list() {
  local wd="$1" repo="$2" resolved="${3:-}"
  if [[ -f "$wd/work.jsonl" ]] && command -v jq >/dev/null 2>&1; then
    jq -rs --arg repo "$repo" --arg res "$resolved" '
      ($res|split(" ")|map(select(length>0))) as $r
      | [ .[] | select(.type=="relay_sent" or .type=="relay_received")
          | {dir:(if .type=="relay_sent" then "outbound" else "inbound" end), slug:.slug, peer:(.to // .from // "—")} ]
      | map(select(.slug as $s | ($r|index($s))|not))
      | .[] | "  \($repo): \(.dir) \(.peer) — \(.slug)"' < "$wd/work.jsonl"
  elif [[ -d "$wd/upstream" ]]; then
    find "$wd/upstream" -maxdepth 1 \( -name 'from-*.md' -o -name 'to-*.md' \) 2>/dev/null \
      | sed "s|.*/||; s|^|  ${repo}: |"
  fi
}

# inject_block <file> <begin-marker> <end-marker> <content-file>
# Replaces the region between the markers with the content; if the markers are
# absent, appends them (with content) at end of file. Deterministic, in-place.
inject_block() {
  local file="$1" begin="$2" end="$3" cf="$4"
  if grep -qF "$begin" "$file"; then
    awk -v b="$begin" -v e="$end" -v cf="$cf" '
      index($0,b){ print; while((getline line < cf)>0) print line; close(cf); skip=1; next }
      index($0,e){ skip=0; print; next }
      !skip { print }
    ' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
  else
    { echo ""; echo "$begin"; cat "$cf"; echo "$end"; } >> "$file"
  fi
}

# discover_children <epic-id>  -> "repo|wid" per work item whose log declares this epic.
# Membership is DERIVED: each child declares its epic at creation
# (wlog.sh created ... epic=<id>), so the epic never hand-maintains a roster.
# Sorted + de-duped. (render falls back to the manifest table for legacy epics.)
discover_children() {
  local epic_id="$1" f wd wid repo belongs
  command -v jq >/dev/null 2>&1 || return 0
  for f in "$ROOT"/docs/work/*/work.jsonl "$ROOT"/repos/*/docs/work/*/work.jsonl; do
    [[ -f "$f" ]] || continue
    belongs="$(jq -rs --arg e "$epic_id" 'any(.[]; (.type=="created" or .type=="meta_changed") and (.epic==$e))' < "$f" 2>/dev/null || echo false)"
    [[ "$belongs" == "true" ]] || continue
    wd="$(dirname "$f")"; wid="$(basename "$wd")"
    repo="$(jq -rs 'map(select(.type=="created"))[0].repo // empty' < "$f" 2>/dev/null)"
    if [[ -z "$repo" ]]; then
      if [[ "$wd" == "$ROOT/repos/"* ]]; then repo="${wd#"$ROOT"/repos/}"; repo="${repo%%/*}"; else repo="solution"; fi
    fi
    echo "$repo|$wid"
  done | sort -u
}

# epic_resolved_slugs <epic-id> -> space-separated set of slugs that carry ANY relay_resolved
# event in ANY of the epic's child logs. This is the epic-global "settled relays" set the A1
# rule (see relay_counts) uses to close BOTH legs of a relay from a single resolution — so a
# source's outbound leg auto-closes when the target resolves, without the source emitting its
# own relay_resolved. Scans the same file set as discover_children.
epic_resolved_slugs() {
  local epic_id="$1" f
  command -v jq >/dev/null 2>&1 || return 0
  for f in "$ROOT"/docs/work/*/work.jsonl "$ROOT"/repos/*/docs/work/*/work.jsonl; do
    [[ -f "$f" ]] || continue
    # Feed the file to jq via STDIN, never as a path arg — see the CROSS-PLATFORM note up top.
    jq -rs --arg e "$epic_id" '
      if any(.[]; (.type=="created" or .type=="meta_changed") and (.epic==$e))
      then ( .[] | select(.type=="relay_resolved") | .slug )
      else empty end' < "$f" 2>/dev/null
  done | tr -d '\r' | sort -u | tr '\n' ' '
}

render() {
  local EPIC_DIR EPIC_MD EPIC_ID EPIC_TITLE
  EPIC_DIR="$(resolve_epic "$EPIC_ARG")" || exit 1
  EPIC_MD="$EPIC_DIR/manifest.md"
  EPIC_ID="$(basename "$EPIC_DIR")"
  EPIC_TITLE="$(awk -F'— ' '/^# Epic:/{print $2; exit}' "$EPIC_MD")"
  local EPIC_PHASE; EPIC_PHASE="$(awk -F': ' '/^\*\*Epic Phase\*\*:/{print $2; exit}' "$EPIC_MD" | sed 's/ *$//')"
  # A1: epic-global set of settled relay slugs — one resolution closes both legs (see relay_counts).
  local RESOLVED; RESOLVED="$(epic_resolved_slugs "$EPIC_ID")"
  local WISH; WISH="$(awk -F': ' '/^\*\*Wishlist\*\*:/{print $2; exit}' "$EPIC_MD" | sed 's/ *$//')"
  # "Last Synced" was removed from the manifest in the event-log rewrite; show the
  # authored "Last Updated" instead (sync-time is no longer a stored field).
  local UPDATED; UPDATED="$(awk -F': ' '/^\*\*Last Updated\*\*:/{print $2; exit}' "$EPIC_MD" | cut -c1-10)"

  # Membership: DERIVED from child logs (each declares epic=<id> at creation).
  # Legacy fallback: parse the manifest's Tracked Repos table for older epics
  # whose children predate the event log.
  local ROWS; ROWS="$(discover_children "$EPIC_ID")"
  if [[ -z "$ROWS" ]]; then
    ROWS="$(awk '
      /^## Tracked Repos/{intable=1; next}
      /^## /{ if(intable) exit }
      intable && /^\| / {
        n=split($0,c,"|");
        repo=c[2]; wid=c[3]; phase=c[4];
        gsub(/^[ \t]+|[ \t]+$/,"",repo); gsub(/^[ \t]+|[ \t]+$/,"",wid); gsub(/^[ \t]+|[ \t]+$/,"",phase);
        if(repo=="Repo" || repo ~ /^-+$/ || repo=="") next;
        print repo "|" wid "|" phase;
      }' "$EPIC_MD")"
  fi

  # gather per-repo state
  local base=99 total_open=0
  local -a R_repo R_wid R_phase R_done R_in R_out R_state
  local i=0
  while IFS='|' read -r repo wid phasecell; do
    [[ -n "$repo" ]] || continue
    local wd; wd="$(work_dir "$repo" "$wid")"
    # Epic Phase Done: prefer the event log (last phase_done); fall back to the
    # generated manifest field, then the legacy table cell.
    local donejson=""
    [[ -f "$wd/work.jsonl" ]] && command -v jq >/dev/null 2>&1 && \
      donejson="$(jq -rs 'map(select(.type=="phase_done")|.phase)|(last // "")' < "$wd/work.jsonl" 2>/dev/null)"
    local donefield=""
    [[ -z "$donejson" && -f "$wd/manifest.md" ]] && donefield="$(awk -F': ' '/^\*\*Epic Phase Done\*\*:/{print $2; exit}' "$wd/manifest.md" | sed 's/ *$//')"
    local doneword="${donejson:-${donefield:-$phasecell}}"
    local dord; dord="$(phase_ord "$doneword")"
    local oin oout; read -r oin oout < <(relay_counts "$wd" "$RESOLVED")
    R_repo[$i]="$repo"; R_wid[$i]="$wid"; R_phase[$i]="$doneword"; R_done[$i]="$dord"; R_in[$i]="$oin"; R_out[$i]="$oout"
    (( dord < base )) && base=$dord
    total_open=$(( total_open + oin + oout ))
    i=$(( i+1 ))
  done <<< "$ROWS"
  local n=$i
  (( base==99 )) && base=0
  local target=$(( base + 1 )); (( target > 5 )) && target=5

  # ---- unambiguous barrier label -------------------------------------------
  # The persisted "**Epic Phase**" field used to be the bare SETTLED-FLOOR name
  # (e.g. "planning"), which reads as "we are IN planning, do not implement" —
  # even when the barrier is actually OPEN to the next phase. That ambiguity
  # made some repos hold while others proceeded. The label now always NAMES THE
  # WORKABLE PHASE and its GATE explicitly:
  #   "<phase> (OPEN)"  -> every repo MAY run <phase> now (this is the go signal)
  #   "<phase> (HELD)"  -> blocked: relays in flight; nobody starts <phase> yet
  #   "complete"        -> validation settled everywhere, zero relays
  # BARRIER_SHORT feeds the header; BARRIER_LONG (with the reason) is persisted.
  local BARRIER_SHORT BARRIER_LONG
  if (( base >= 4 && total_open == 0 )); then
    BARRIER_SHORT="complete"; BARRIER_LONG="complete"
  elif (( total_open > 0 )); then
    local _hp; _hp="$(phase_name $(( target > 4 ? 4 : target )))"
    BARRIER_SHORT="$_hp (HELD)"
    BARRIER_LONG="$_hp — HELD ($total_open open relay(s); resolve them before any repo starts $_hp)"
  else
    local _tp; _tp="$(phase_name $target)"
    BARRIER_SHORT="$_tp (OPEN)"
    if (( base == 0 )); then
      BARRIER_LONG="$_tp — OPEN (kickoff — every repo may run $_tp now)"
    else
      BARRIER_LONG="$_tp — OPEN (all repos settled $(phase_name $base), zero open relays — every repo may run $_tp now)"
    fi
  fi

  # per-repo state label
  for ((j=0;j<n;j++)); do
    if (( ${R_in[$j]} > 0 )); then R_state[$j]="🟢 ACT — ${R_in[$j]} inbound ask(s); answer + reply"
    elif (( ${R_out[$j]} > 0 )); then R_state[$j]="⏳ BLOCKED — ${R_out[$j]} reply pending (run /epic sync)"
    elif (( ${R_done[$j]} >= 4 )); then R_state[$j]="✅ complete (validated)"
    elif (( ${R_done[$j]} == base )); then R_state[$j]="🔵 WORKING — owes $(phase_name $target)"
    else R_state[$j]="✅ settled @ $(phase_name ${R_done[$j]}) (at barrier)"; fi
  done

  # ---- header ----
  printf '\033[1m%s\033[0m\n' "EPIC $EPIC_ID"
  [[ -n "$EPIC_TITLE" ]] && printf '  %s\n' "$EPIC_TITLE"
  printf '  barrier: \033[1m%s\033[0m   ·   wishlist: %s   ·   last updated: %s\n' "$BARRIER_SHORT" "${WISH:-—}" "${UPDATED:---}"
  printf '%s\n' "────────────────────────────────────────────────────────────────────────────"
  printf '%-14s %-34s %-14s %s\n' "REPO" "WORK ITEM" "DONE" "STATE"
  for ((j=0;j<n;j++)); do
    printf '%-14s %-34s %-14s %s\n' "${R_repo[$j]}" "${R_wid[$j]:0:34}" "${R_phase[$j]}" "${R_state[$j]}"
  done
  printf '%s\n' "────────────────────────────────────────────────────────────────────────────"

  # ---- NEXT ----
  local NEXT="" STATEMSG=""
  if (( total_open > 0 )); then
    STATEMSG="⏳ Settling $(phase_name $target) — relays in flight (barrier held)"
    # count repos with an open inbound ask (they unblock the chain)
    local nact=0
    for ((j=0;j<n;j++)); do (( ${R_in[$j]} > 0 )) && nact=$(( nact + 1 )); done
    if (( nact > 0 )); then
      NEXT="👉 act in the $nact 🟢 ACT repo(s) — see 'run in each repo' below for the exact command per repo; then /epic sync at root."
    else
      NEXT="👉 run  /epic sync  at the solution root to deliver $total_open pending relay(s)."
    fi
  elif (( base >= 4 )); then
    # validation is the terminal phase — every tracked repo has settled it (and zero
    # open relays, or we'd be in the settling branch above) ⇒ the epic is complete.
    STATEMSG="✅ All repos settled validation — epic complete."
    NEXT="🎉 Epic complete — set the epic manifest Status: Completed (and /epic next-milestone if wishlist-linked)."
  else
    STATEMSG="▶ $(phase_name $base) settled — barrier OPEN, advance to $(phase_name $target)"
    local laggards=""
    for ((j=0;j<n;j++)); do (( ${R_done[$j]} == base )) && laggards+="${R_repo[$j]} "; done
    NEXT="👉 advance ${laggards% } to $(phase_name $target) — see 'run in each repo' below for the exact command per repo."
  fi
  printf '%s\n' "$STATEMSG"
  printf '\033[1m%s\033[0m\n' "$NEXT"

  # ---- open relay detail ----
  if (( total_open > 0 )); then
    printf '%s\n' "open relays:"
    for ((j=0;j<n;j++)); do
      local wd; wd="$(work_dir "${R_repo[$j]}" "${R_wid[$j]}")"
      relay_list "$wd" "${R_repo[$j]}" "$RESOLVED"
    done
  fi

  # ---- per-repo action commands (ALWAYS emitted) --------------------------
  # For every repo that has in-repo work to do — 🟢 ACT (open inbound ask) or
  # 🔵 WORKING (owes the barrier's next phase) — print the exact, copy-pasteable
  # command: which dir to open a Claude session in, and the slash command with
  # the real work id. ACT repos also get the exact relay_resolved close command.
  # Repos that are ⏳ BLOCKED (own the outbound, waiting on replies) or already
  # at the barrier are intentionally omitted — their next move is `/epic sync`.
  local any_act=0 printed_hdr=0
  for ((j=0;j<n;j++)); do
    local owed=0
    if   (( ${R_in[$j]} > 0 )); then owed=$target                                  # ACT: do the owed phase, then resolve
    elif (( ${R_out[$j]} == 0 && ${R_done[$j]} < target && ${R_done[$j]} < 4 )); then owed=$target  # WORKING: owes the barrier target (validation=4 is terminal)
    else continue; fi
    if (( printed_hdr == 0 )); then
      printf '%s\n' "run in each repo (open a Claude session in the dir, then run the command):"
      printed_hdr=1
    fi
    local cwd cmd; cwd="$(repo_cwd "${R_repo[$j]}")"; cmd="$(phase_slash "$owed" "${R_wid[$j]}" "${R_repo[$j]}")"
    printf '  %-13s cd %-22s → in Claude:  %s\n' "${R_repo[$j]}" "$cwd" "$cmd"
    if (( ${R_in[$j]} > 0 )); then
      any_act=1
      local wd slugs s; wd="$(work_dir "${R_repo[$j]}" "${R_wid[$j]}")"; slugs="$(open_inbound_slugs "$wd" "$RESOLVED")"
      for s in $slugs; do
        printf '  %-13s   then close inbound: scripts/wlog.sh docs/work/%s relay_resolved direction=inbound slug=%s && scripts/wrender.sh docs/work/%s\n' \
          "" "${R_wid[$j]}" "$s" "${R_wid[$j]}"
      done
    fi
  done
  if (( any_act == 1 )); then
    printf '%s\n' "then, back at the solution root:  /epic sync $EPIC_ID   (delivers replies, re-derives the barrier)"
  fi

  # ---- --write: inject the derived board into the epic manifest ----
  if (( WRITE )); then
    # BARRIER_LONG names the workable phase + gate (OPEN/HELD/complete) unambiguously —
    # see the barrier-label block above. This is the single go/no-go signal a child repo
    # reads: "<phase> (OPEN)" means that repo may start <phase> now.
    local bf; bf="$(mktemp)"
    {
      printf '**Epic Phase**: %s\n\n' "$BARRIER_LONG"
      printf '| Repo | Work Item | Phase | Status |\n'
      printf '|------|-----------|-------|--------|\n'
      for ((j=0;j<n;j++)); do
        # Status cell: plain-text projection of the per-repo state (emoji stripped is fine to keep).
        printf '| %s | %s | %s | %s |\n' "${R_repo[$j]}" "${R_wid[$j]}" "${R_phase[$j]}" "${R_state[$j]}"
      done
    } > "$bf"
    inject_block "$EPIC_MD" "<!-- BEGIN BOARD -->" "<!-- END BOARD -->" "$bf"
    rm -f "$bf"
    printf '\033[2m%s\033[0m\n' "ⓘ wrote derived board into $EPIC_MD (between BOARD anchors)."
  else
    printf '\033[2m%s\033[0m\n' "ⓘ read-only snapshot. Run with --write to refresh the epic manifest board, or /epic board (Claude) to sync-then-show."
  fi
}

if (( WATCH )); then
  while true; do clear; render; printf '\n(refreshing every 5s · Ctrl-C to exit)\n'; sleep 5; done
else
  render
fi
