#!/usr/bin/env bash
# windex.sh — regenerate a work-item registry (index.md) for a docs/work root.
#
# Usage:
#   scripts/windex.sh [work-root]        # default work-root: docs/work
#   scripts/windex.sh repos/orchestrator/docs/work
#
# Contract (see docs/dev/decisions/append-only-work-event-log.md):
#   * PURE PROJECTION. Deterministic: same inputs → byte-identical index.md.
#   * It reads each item's GENERATED manifest.md (which scripts/wrender.sh folds
#     from work.jsonl) and harvests the already-rendered fields. The status/emoji
#     vocabulary lives ONLY in wrender.sh — windex never re-derives it.
#   * The registry is a GENERATED VIEW. Never hand-edit index.md; re-run this
#     after wlog.sh/wrender.sh (or from a hook) to refresh it.
#
# Rows are sorted by Last Updated (desc), then work-id (asc) — stable + deterministic.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "$SCRIPT_DIR/lib/common.sh" ]]; then
  # shellcheck source=/dev/null
  source "$SCRIPT_DIR/lib/common.sh"
else
  log_error() { echo "[ERROR] $*" >&2; }
  log_info()  { echo "[INFO]  $*" >&2; }
fi

WORK_ROOT="${1:-docs/work}"
WORK_ROOT="${WORK_ROOT%/}"
[[ -d "$WORK_ROOT" ]] || { log_error "not a directory: $WORK_ROOT"; exit 1; }
OUT="$WORK_ROOT/index.md"

# field <manifest> <label>  -> value after a "**label**: " header line ("" if absent)
field() {
  awk -v L="$2" 'index($0,"**"L"**:")==1 { sub(/^[^:]*: */,""); print; exit }' "$1"
}

TMP="$(mktemp)"; trap 'rm -f "$TMP" "$OUT.tmp"' EXIT
# each line: <updated>\t<id>\t<markdown-row>   (first two are sort keys, dropped on output)
for mf in "$WORK_ROOT"/*/manifest.md; do
  [[ -f "$mf" ]] || continue
  dir="$(dirname "$mf")"; id="$(basename "$dir")"
  title="$(awk -F'# Work Item: ' '/^# Work Item: /{print $2; exit}' "$mf")"
  status="$(field "$mf" Status)";            [[ -n "$status"  ]] || status="—"
  epic="$(field "$mf" Epic)";                [[ -n "$epic"    ]] || epic="—"
  phase="$(field "$mf" 'Epic Phase Done')";  [[ -n "$phase"   ]] || phase="—"
  updated="$(field "$mf" 'Last Updated')";   [[ -n "$updated" ]] || updated="—"
  printf '%s\t%s\t| [%s](./%s/manifest.md) | %s | %s | %s | %s | %s |\n' \
    "$updated" "$id" "$id" "$id" "${title:-—}" "$status" "$epic" "$phase" "$updated" >> "$TMP"
done

count=$(wc -l < "$TMP" | tr -d ' ')
{
  echo "# Work Items"
  echo ""
  echo "<!-- GENERATED by scripts/windex.sh — DO NOT EDIT BY HAND. Run: scripts/windex.sh $WORK_ROOT -->"
  echo ""
  if [[ "$count" -eq 0 ]]; then
    echo "_No work items yet._"
  else
    echo "| Work Item | Title | Status | Epic | Epic Phase Done | Updated |"
    echo "|-----------|-------|--------|------|-----------------|---------|"
    sort -t"$(printf '\t')" -k1,1r -k2,2 "$TMP" | cut -f3-
  fi
} > "$OUT.tmp"
mv "$OUT.tmp" "$OUT"
log_info "wrote $OUT ($count item(s))"
