#!/usr/bin/env bash
# kb-extract.sh <repo-root> — deterministic contract-surface + structure enumeration → docs/kb/self/extract/.
# DETECTS artifacts/formats/git facts; NEVER comprehends code (that's DRAFT's job). Language/layout-agnostic.
# Regenerated wholesale each run. No LLM. (Phase 2 / FR-4.0, FR-1.6①)
set -uo pipefail
ROOT="${1:-.}"
OUT="$ROOT/docs/kb/self/extract"
BANNER='<!-- GENERATED by kb-extract.sh — internal grounding, not consumer content. -->'
mkdir -p "$OUT"

# Tracked files only (respects .gitignore; falls back to find if not a git repo).
list_files() {
  if git -C "$ROOT" rev-parse >/dev/null 2>&1; then git -C "$ROOT" ls-files
  else (cd "$ROOT" && find . -type f | sed 's|^\./||'); fi
}
mapfile -t FILES < <(list_files | LC_ALL=C sort)

# Optional kb-config exclude globs (best-effort; simple substring/glob match).
EXCL=()
CFG="$ROOT/docs/kb/kb-config.yaml"
[ -f "$CFG" ] && mapfile -t EXCL < <(awk '/^exclude:/{e=1;next} e&&/^[[:space:]]+-/{sub(/^[[:space:]]+-[[:space:]]*/,"");gsub(/^["'\'']+|["'\'']+$/,"");print;next} e&&/^[^[:space:]]/{e=0}' "$CFG")
excluded() { local p="$1" g; for g in "${EXCL[@]:-}"; do [ -n "$g" ] || continue; case "$p" in ${g}) return 0;; esac; done; return 1; }

# (a) CONTRACT-ARTIFACT INVENTORY — the load-bearing output. Detection by FORMAT, not by language.
{
  printf '# Contract artifacts\n%s\n\n' "$BANNER"
  printf '## Protobuf / gRPC\n';        for f in "${FILES[@]}"; do case "$f" in *.proto) excluded "$f"||echo "- $f";; esac; done
  printf '\n## OpenAPI / Swagger\n';    for f in "${FILES[@]}"; do case "$f" in *.yaml|*.yml|*.json) excluded "$f" && continue; grep -qiE '^(openapi|swagger):' "$ROOT/$f" 2>/dev/null && echo "- $f";; esac; done
  printf '\n## GraphQL\n';              for f in "${FILES[@]}"; do case "$f" in *.graphql|*.gql) excluded "$f"||echo "- $f";; esac; done
  printf '\n## JSON Schema\n';          for f in "${FILES[@]}"; do case "$f" in *.json) excluded "$f" && continue; grep -qE '"\$schema"|"\$id"' "$ROOT/$f" 2>/dev/null && echo "- $f";; esac; done
  printf '\n## SQL migrations\n';       for f in "${FILES[@]}"; do case "$f" in *migrat*/*.sql) excluded "$f"||echo "- $f";; esac; done
} > "$OUT/contracts.md"

# (b) DEPENDENCY MANIFESTS — by filename (finite known set).
{
  printf '# Dependency manifests\n%s\n\n' "$BANNER"
  for f in "${FILES[@]}"; do case "$(basename "$f")" in
    go.mod|package.json|Cargo.toml|pom.xml|build.gradle|requirements.txt|pyproject.toml|Gemfile|composer.json) excluded "$f"||echo "- $f";;
  esac; done
} > "$OUT/manifests.md"

# (c) COARSE STRUCTURE MAP — dirs, entry files. STRUCTURAL, not a capability map (capabilities = DRAFT).
{
  printf '# Structure map\n%s\n\n' "$BANNER"
  printf '## Top-level directories\n'
  printf '%s\n' "${FILES[@]}" | awk -F/ 'NF>1{print $1}' | LC_ALL=C sort -u | sed 's/^/- /'
  printf '\n## Likely entry points\n'
  for f in "${FILES[@]}"; do case "$(basename "$f")" in
    main.go|main.rs|main.ts|main.py|index.ts|index.js|server.go|app.go|mod.rs|lib.rs|__main__.py) excluded "$f"||echo "- $f";;
  esac; done
} > "$OUT/structure.md"

# (d) GIT FACTS — HEAD, language histogram, churn (cheap importance proxy). Language-agnostic.
{
  printf '# Git facts\n%s\n\n' "$BANNER"
  if git -C "$ROOT" rev-parse >/dev/null 2>&1; then
    printf '## HEAD\n- %s\n\n' "$(git -C "$ROOT" rev-parse --short HEAD)"
    printf '## Language histogram (by extension, tracked files)\n'
    printf '%s\n' "${FILES[@]}" | awk -F. 'NF>1{print $NF}' | LC_ALL=C sort | uniq -c | sort -rn | head -15 | awk '{printf "- %s: %s\n",$2,$1}'
    printf '\n## Most-churned files (last 200 commits — importance proxy)\n'
    git -C "$ROOT" log --pretty=format: --name-only -n 200 2>/dev/null | grep -vE '^[[:space:]]*$' | LC_ALL=C sort | uniq -c | sort -rn | head -15 | awk '{printf "- %s (%s)\n",$2,$1}'
  else
    printf 'UNKNOWN — not a git repository\n'
  fi
} > "$OUT/git-facts.md"

# (e) DOC-vs-CODE PATH DIVERGENCE (ADVISORY — non-authoritative). Pure pattern detection:
# URL-path-shaped tokens named in the repo's OWN docs (README/CLAUDE.md/AGENTS.md) but NOT found
# verbatim in tracked source. A CANDIDATE list for DRAFT's "code over docs" check — it CANNOT know a
# path is unimplemented (grep misses paths built by string concatenation; a doc path may be
# illustrative prose). Never a lint FAIL. Still NEVER comprehends code — no route parsing (FR-4).
{
  printf '# Doc-vs-code path divergence (ADVISORY — non-authoritative)\n%s\n\n' "$BANNER"
  printf '_Candidate list only: URL-path-shaped tokens that appear in this repo'\''s own docs\n'
  printf '(README/CLAUDE.md/AGENTS.md) but not found verbatim in tracked source. A hit may be\n'
  printf 'illustrative prose or a path assembled by string concatenation in code. DRAFT MUST confirm\n'
  printf 'each against the actual code before treating it as an over-claim (code over docs)._\n\n'

  # Partition tracked, non-excluded files into the repo's own docs vs. everything else (source).
  DOCS=(); SRC=()
  for f in "${FILES[@]}"; do
    excluded "$f" && continue
    case "$(basename "$f")" in
      README|README.*|CLAUDE.md|AGENTS.md) DOCS+=("$ROOT/$f");;
      *) case "$f" in *.md|*.markdown|*.txt|*.rst) ;; *) SRC+=("$ROOT/$f");; esac;;
    esac
  done

  # Emit multi-segment URL-path-shaped tokens (busybox-safe: -h -o -E, ERE only, no -P).
  extract_paths() {
    [ "$#" -gt 0 ] || return 0
    grep -hoE '/[A-Za-z][A-Za-z0-9_.:{}-]*(/[A-Za-z0-9_.:{}-]+)+' "$@" 2>/dev/null \
      | grep -vE '\.(md|markdown|txt|go|rs|ts|tsx|js|jsx|py|json|yaml|yml|sql|sh|png|jpg|svg|html|css)$' \
      | LC_ALL=C sort -u
  }

  if [ "${#DOCS[@]}" -gt 0 ]; then
    docpaths="$(extract_paths "${DOCS[@]}")"
    srcpaths="$(extract_paths "${SRC[@]:-}")"
    hits=0
    while IFS= read -r p; do
      [ -n "$p" ] || continue
      printf '%s\n' "$srcpaths" | grep -qxF "$p" || { printf -- '- `%s` — in docs, not found verbatim in source\n' "$p"; hits=$((hits+1)); }
    done <<EOF
$docpaths
EOF
    [ "$hits" -eq 0 ] && printf '_No divergent path tokens detected._\n'
  else
    printf '_No repo docs (README/CLAUDE.md/AGENTS.md) found — nothing to cross-check._\n'
  fi
} > "$OUT/doc-vs-code.md"

echo "kb-extract: wrote $OUT/{contracts,manifests,structure,git-facts,doc-vs-code}.md" >&2
# NOTE: optional tree-sitter signature layer intentionally not in v1 (graceful degradation — FR-4.0).
