#!/usr/bin/env bash
# kb-render.sh <repo-root> — regenerate docs/kb/index.md and every collection dir's index.md
# as PURE PROJECTIONS of the concept frontmatter. Byte-identical output for identical input
# (no wall-clock time in output). Deterministic; no LLM. (Phase 2 / FR-4.2)
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_kb_lib.sh
. "$HERE/_kb_lib.sh"

ROOT="${1:-.}"
KB="$ROOT/docs/kb"
BANNER='<!-- GENERATED by kb-render.sh — DO NOT EDIT BY HAND. -->'
[ -d "$KB" ] || { echo "kb-render: no $KB (nothing to render)" >&2; exit 0; }

# Deterministic freshness anchor for the top-level index: the HEAD the KB was generated against.
# BOTH values are pure functions of the current commit (short sha + committer date %cs = YYYY-MM-DD),
# so identical tree ⇒ identical output — no wall-clock, §4.5 byte-idempotence preserved.
# Non-git ⇒ UNKNOWN (mirrors kb-stamp.sh's fallback).
SHA="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo UNKNOWN)"
CDATE="$(git -C "$ROOT" log -1 --format=%cs 2>/dev/null || echo UNKNOWN)"

# One concept as an index list item: "- [Title](./file.md) — `type` — description"
concept_line() {
  local f="$1" base title type desc
  base="$(basename "$f")"
  title="$(kb_fm_scalar "$f" title)"; [ -z "$title" ] && title="${base%.md}"
  type="$(kb_fm_scalar "$f" type)"; [ -z "$type" ] && type="note"
  desc="$(kb_fm_scalar "$f" description)"
  printf -- '- [%s](./%s) — `%s`%s\n' "$title" "$base" "$type" "${desc:+ — $desc}"
}

# Per-directory index for a collection directory (capabilities/, interfaces/, ...).
gen_dir_index() {
  local dir="$1" out="$1/index.md" f
  {
    printf '# Index — %s\n%s\n\n' "$(basename "$dir")" "$BANNER"
    while IFS= read -r f; do concept_line "$f"; done \
      < <(find "$dir" -maxdepth 1 -type f -name '*.md' ! -name 'index.md' | LC_ALL=C sort)
  } > "$out"
}

# Collections = directories under self/ that hold concept files (skip extract/, which is machine grounding).
while IFS= read -r d; do
  ls "$d"/*.md >/dev/null 2>&1 || continue
  gen_dir_index "$d"
done < <(find "$KB/self" -mindepth 1 -type d ! -path '*/extract*' ! -path '*/eval*' 2>/dev/null | LC_ALL=C sort)

# Top-level KB index.
repo="$(kb_fm_scalar "$KB/self/overview.md" repo 2>/dev/null || true)"; [ -z "$repo" ] && repo="$(basename "$(cd "$ROOT" && pwd)")"
{
  printf '# Knowledge base — %s\n%s\n\n' "$repo" "$BANNER"
  printf 'Last synced: %s @ %s — schema/content changes after this commit are NOT reflected. See `log.md`.\n\n' "$CDATE" "$SHA"
  printf 'Business-logic summaries for a peer repo. Start with `self/capabilities/`.\n\n'
  printf '## Self\n\n'
  # Canonical singular concerns first, in curated narrative order.
  for n in overview context glossary; do
    f="$KB/self/$n.md"; [ -f "$f" ] && printf -- '- [%s](./self/%s.md)\n' "$n" "$n"
  done
  # Any OTHER single-file concept directly under self/ — a collection that started as one file per
  # the layout growth rule (gotchas.md, decisions.md, interfaces.md) before promotion. Surfaced here
  # so "lint-clean ⇒ index-reachable" holds. Sorted; deterministic; emits nothing in the common case.
  while IFS= read -r f; do
    n="$(basename "$f")"; n="${n%.md}"
    case "$n" in overview|context|glossary) continue;; esac
    printf -- '- [%s](./self/%s.md)\n' "$n" "$n"
  done < <(find "$KB/self" -maxdepth 1 -type f -name '*.md' ! -name 'index.md' 2>/dev/null | LC_ALL=C sort)
  printf '\n## Collections\n\n'
  while IFS= read -r d; do
    [ -f "$d/index.md" ] || continue
    b="$(basename "$d")"; printf -- '- [%s](./self/%s/index.md)\n' "$b" "$b"
  done < <(find "$KB/self" -mindepth 1 -type d ! -path '*/extract*' ! -path '*/eval*' 2>/dev/null | LC_ALL=C sort)
} > "$KB/index.md"

echo "kb-render: wrote $KB/index.md + collection indexes" >&2
